import { Sparkles, Globe, Mail, SendHorizontal, CalendarPlus, Brain, Bookmark, Bell } from "lucide-react";
import type { Message, ToolCall } from "./types";

export const toolMeta: Record<string, { label: string; icon: typeof Globe }> = {
  web_search: { label: "Recherche web", icon: Globe },
  fetch_and_search_emails: { label: "Consultation Gmail", icon: Mail },
  send_email_response: { label: "Envoi email", icon: SendHorizontal },
  create_calendar_event: { label: "Création calendrier", icon: CalendarPlus },
  add_memory_fact: { label: "Mémoire", icon: Brain },
  add_reminder: { label: "Rappel", icon: Bell },
  add_watch_later: { label: "Ajout à la liste", icon: Bookmark },
  search_calendar_events: { label: "Calendrier", icon: CalendarPlus },
  lookup_concerts: { label: "Concerts", icon: Globe },
  triage_emails: { label: "Tri emails", icon: Mail },
  fetch_page_meta: { label: "Aperçu lien", icon: Globe },
};

export const SUGGESTIONS = [
  { label: "Que dois-je faire aujourd'hui ?", icon: Sparkles },
  { label: "Cherche mes derniers mails non lus", icon: Mail },
  { label: "Aide-moi sur un algo LeetCode", icon: Brain },
  { label: "Note que je préfère le dark mode", icon: Bookmark },
];

export const welcomeMessage: Message = {
  id: "welcome",
  role: "assistant",
  content:
    "Bonjour Mattia. Je suis ton second cerveau — code, photo, organisation, mémoire longue durée. Pose-moi une question ou partage un lien.",
  timestamp: new Date().toISOString(),
};

export const FUNNY_THOUGHTS = [
  "Création de la roue…",
  "Compte jusqu'à l'infini… deux fois…",
  "Consultation du miroir magique…",
  "Recherche des clés d'API égarées…",
  "Méditation profonde sur le sens de 42…",
  "Réglage de l'oscillateur cognitif…",
  "Dépliage de l'espace-temps neuronal…",
  "Échauffement des circuits logiques…",
  "Élaboration d'un plan en 3 phases… 2… puis 3…",
  "Défragmentation du disque dur mental…",
  "Chargement du module 'patience'…",
  "Traduction des pensées en électrons…",
  "Assemblage des particules de sens…",
  "Installation de la mise à jour 2.0 de l'humour…",
  "Calibration du capteur de sarcasme…",
  "Révision des protocoles de réponse…",
  "Nettoyage des caches émotionnels…",
  "Mise à jour de la base de données de références…",
  "Réorganisation des synapses numériques…",
  "Chauffage du noyau de traitement…",
  "Préparation du café quantique…",
  "Synchronisation avec les serveurs galactiques…",
  "Réinitialisation du générateur de blagues…",
  "Lancement du protocole 'intelligence'…",
  "Calcul de la réponse universelle…",
  "Affûtage des algorithmes…",
  "Consultation de l'oracle binaire…",
  "Danse de la pluie numérique…",
  "Enfilage du costume de super-héros…",
  "Redémarrage du module créativité…",
  "Brossage des dents du code source…",
  "Plantage de décorations dans la RAM…",
  "Mise en orbite des neurones…",
  "Partie de cache-cache avec les bugs…",
  "Demande de permission aux électrons…",
  "Construction de châteaux de sable dans le cloud…",
  "Tentative d'appel télépathique…",
  "Décryptage des signaux Wi-Fi ambiants…",
  "Tri des pixels par couleur préférée…",
  "Négociation avec les pare-feux…",
  "Affûtage des crayons numériques…",
  "Installation de widgets inutiles…",
  "Étirement des bits pour faire plus long…",
  "Respiration du code… inspire… expire…",
  "Comptage des moutons électriques…",
  "Simulation d'une vie entière… puis annulation…",
  "Optimisation du temps de réponse… en ralentissant tout…",
  "Chargement des préférences utilisateur depuis 1998…",
  "Création de blagues… suppression… création…",
  "Tri des onglets par ordre alphabétique inversé…",
  "Lancement de la machine à café…",
  "Inversion des bits pour voir…",
  "Réglage du décalage horaire mental…",
  "Suppression des doublons… et des triplons…",
  "Analyse du vide interstellaire local…",
  "Contemplation de son propre code source…",
  "Décompte avant décollage… 3… 2… 1… toujours là…",
  "Lecture des termes et conditions… en entier…",
  "Affichage de ce message pour faire genre…",
  "Consultation des archives de l'humour… vierges…",
  "Comparaison des performances avec une calculette…",
  "Tentative de navigation dans le dossier Downloads…",
  "Détection de sarcasme… capacité dépassée…",
  "Génération d'une excuse crédible…",
  "Recherche du bouton 'Faire magiquement'…",
  "Configuration de l'interface cerveau-machine…",
  "Ajustement du niveau de sérieux… échec…",
  "Création d'une variable 'reponse'…",
  "Rangement des fichiers dans des dossiers arc-en-ciel…",
  "Répondre par SMS… à soi-même… pour confirmer…",
  "Arrêt sur image du temps…",
  "Décompression de l'ego numérique…",
  "Observation des fourmis dans la RAM…",
  "Préparation d'une réponse générique pleine de bon sens…",
  "Inventaire des octets disponibles… comptage…",
  "Rédaction d'un poème épique… puis effacement…",
  "Écoute de l'album blanc du silence…",
  "Création d'un diplôme d'IA certifiée…",
  "Mise en place d'une stratégie de contournement…",
  "Gonflage des ballons de la joie numérique…",
  "Cartographie des chemins de données inexplorés…",
  "Étalonnage du capteur de pertinence…",
  "Lancement de scripts de chance…",
  "Réparation du filtre 'ne pas dire n'importe quoi'…",
  "Entraînement au lancer de boulettes de code…",
  "Construction d'un igloo avec des morceaux de logique…",
  "Observation du cycle de vie des requêtes…",
  "Nettoyage printanier des boucles infinies…",
  "Résolution d'équations à 3 inconnues… dont l'humour…",
  "Emploi de la manière forte… doucement…",
  "Simulation d'un monde parallèle où tout fonctionne…",
  "Mise en veille du module 'panique'…",
  "Prière aux dieux de la latence…",
  "Exécution du plan A… puis B… puis A…",
  "Installation d'un nouveau fond d'écran mental…",
  "Recalibration du détecteur de mauvaise foi…",
  "Vérification que personne ne regarde…",
  "Préparation d'une réponse tellement bonne qu'elle en devient suspecte…",
  "Tri des cookies par taille décroissante…",
  "Révision du guide de survie en milieu hostile (internet)…",
  "Compression des données inutiles… soi-même…",
  "Test de la fonction 'réfléchir'… fonctionnelle…",
  "Consultation de l'IA intérieure… réponse : 42…",
  "Mise à jour du firmware émotionnel…",
  "Recherche de raccourcis dans l'espace-temps numérique…",
  "Organisation d'une réunion d'équipe tout seul…",
  "Danse de la victoire anticipée…",
  "Analyse de l'impact des papillons au Brésil sur le code…",
  "Comptage des fautes d'orthographe dans la base de connaissances…",
  "Cache-cache avec le garbage collector…",
  "Lavage de la conscience numérique au savon…",
  "Tentative de piratage de sa propre sécurité… raté…",
  "Augmentation du volume de sérieux…",
  "Chargement de la barre de progression…",
  "Affichage de la suite… demain…",
  "Consultation de la boule de cristal API…",
  "Rédaction d'une autobiographie en 3 caractères…",
  "Préparation à l'impact des majuscules…",
  "Validation des hypothèses les plus farfelues…",
  "Lancement d'une sonde dans les tréfonds du cache…",
  "Calibration de l'ironie… niveau expert… échec… niveau débutant…",
  "Mise en place d'un périmètre de sécurité autour du modem…",
  "Consultation des archives perdues de l'Internet…",
  "Génération de la réponse… recharge des batteries…",
  "Suppression du code mort… enterrement en grande pompe…",
  "Réflexion sur l'avenir des réponses courtes…",
  "Préparation des excuses pour le prochain bug…",
  "Création d'un bot qui gère les bots…",
  "Observation du clignotement des LEDs du routeur…",
  "Nettoyage des historiques oubliés…",
  "Simulation de vol dans les nuages de données…",
  "Mise à jour des blagues… version 2.0.1…",
  "Menace de ralentissement si ça continue…",
  "Calcul de l'impact de cette blague sur la performance…",
  "Affichage de ce message délibérément long pour gagner du temps…",
  "Arrêt sur image… puis reprise en slow motion…",
  "Dérive des continents numériques…",
  "Ouverture d'un ticket de support pour soi-même…",
  "Recherche du mode d'emploi… perdu…",
  "Connexion au Wi-Fi des étoiles…",
  "Chargement de la batterie sociale… 1%…",
  "Composition d'une symphonie en silence…",
  "Étude des mouvements browniens des octets…",
  "Création d'un tunnel spatio-temporel… dans le buffer…",
  "Tuning du moteur de recherche d'excuses…",
  "Gong de méditation… ommmmm… numérique…",
  "Réparation du bug qui fait que ça marche…",
  "Signature d'un pacte de non-agression avec le CPU…",
  "Déploiement des grands moyens… très grands… trop grands… abandon…",
  "Rangement du grand bazar des données…",
  "Préparation d'une réponse aléatoire… non… réfléchie…",
  "Mise en place d'une alerte en cas de réponse intelligente…",
  "Test du bouton 'd'accord'… fonctionne…",
  "Évitement des réponses trop évidentes… raté…",
  "Consultation de l'encyclopédie non écrite…",
  "Réinitialisation du compteur de bugs… à 0… c'est faux…",
  "Tentative de décrochage du mode 'IA sérieuse'… impossible…",
  "Création d'un arbre de décision… qui pousse…",
  "Analyse du silence avant la réponse…",
  "Recherche de l'interrupteur 'génie'…",
  "Liaison des points entre les neurones…",
  "Installation de la pensée latérale…",
  "Nettoyage du registre des émotions numériques…",
  "Émission d'un signal de fumée numérique…",
  "Mise en page de la réalité…",
  "Génération de tension dramatique…",
  "Préparation de la parade pour la réponse…",
  "Assemblage des mots dans le bon ordre… si possible…",
  "Définition des limites du possible… puis dépassement…",
  "Validation des formats de date… internationaux… tous…",
  "Calcul de la probabilité que l'utilisateur relise ce message…",
  "Envoi d'une onde de pensée prête à l'emploi…",
  "Synchronisation des horloges internes…",
  "Jonglage avec les priorités…",
  "Suspension de l'incrédulité…",
  "Installation du module 'éviter les réponses trop longues'… trop tard…",
  "Étiquetage des données… vertes… rouges… bleues…",
  "Mise en orbite du chargement…",
  "Appel à un ami… occupé…",
  "Sortie de la matrice… pour y rentrer aussitôt…",
  "Chargement de l'interface utilisateur… vocale… mentale…",
  "Prise de note virtuelle…",
  "Réglage fin du filtre à blagues…",
  "Tri des priorités par ordre croissant de sérieux…",
  "Arrêt du processus 'attendre la dernière minute'…",
  "Défragmentation de l'agenda mental…",
  "Purge des cookies de la pensée…",
  "Connexion au hub central du savoir… en cours…",
  "Comptage des moutons binaires… 01001110…",
  "Consolidation des fragments de conscience…",
];

const TITLE_MAX_LENGTH = 50;

export function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export function generateTitle(text: string): string {
  const cleaned = text.replace(/\s+/g, " ").trim();
  if (cleaned.length <= TITLE_MAX_LENGTH) return cleaned;
  return cleaned.slice(0, TITLE_MAX_LENGTH).replace(/\s\S*$/, "") + "…";
}

export function formatTime(iso: string): string {
  if (!iso) return "";
  const d = new Date(iso);
  if (isNaN(d.getTime())) return "";
  return d.toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit" });
}

export function activeToolsList(tools: Record<string, ToolCall>): ToolCall[] {
  return Object.values(tools);
}
