import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/home/mattia/.cache/ms-playwright/chromium-1223/chrome-linux64/chrome" });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await page.waitForTimeout(3000);
await page.screenshot({ path: "/tmp/landing-top.png" });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight / 2));
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/landing-mid.png" });
await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
await page.waitForTimeout(1500);
await page.screenshot({ path: "/tmp/landing-bottom.png" });
const mob = await browser.newPage({ viewport: { width: 375, height: 812 } });
await mob.goto("http://localhost:3000/", { waitUntil: "networkidle" });
await mob.waitForTimeout(2500);
const overflow = await mob.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
console.log("MOBILE_H_OVERFLOW:", overflow);
await mob.screenshot({ path: "/tmp/landing-mobile.png" });
await browser.close();
